### ISSUE TITLE
Second pair of eyes

### ISSUE THREAD

**Issue by rememberlenny** [rememberlenny/robinhood-ruby#1]
Hey! 

I ported this over from the robinhood-node library last night. 

I'd love your input on the project, as most of you are contributors on it.

@aurbano
@Jspenc72
@nodesocket
@ted7726
@dustinmoorenet
@ialexryan
@vantreeseba
@z123
@busse
@jasontruluck

**Comment by jspenc72** [comment]
Check out robinhood-observer on npm

**Comment by jspenc72** [comment]
I would advise returning an observable so clients can simply listen for updates once the initial request is sent.

**Comment by rememberlenny** [comment]
@jspenc72 Thanks! I'll take a look.
