### ISSUE TITLE
Attempts to set up a client renders an error

### ISSUE THREAD

**Issue by l0010o0001l** [rememberlenny/robinhood-ruby#2]
`@robinhood = Robinhood::REST::Client(username, password)`

Error:
```undefined method `Client' for Robinhood::REST:Module (NoMethodError)```

**Comment by rememberlenny** [comment]
@l0010o0001l Sorry for the delay here. I haven't looked into this since running it a while ago. Its very possible the API that was previously used for this is no longer accessible.

**Comment by rememberlenny** [comment]
@l0010o0001l Fixed in #3
